### ISSUE TITLE
Tabs List plugin does not work well together with Find in Files plugin

### ISSUE THREAD

**Issue by Andreas123456** [CudaText-addons/cuda_tabs_list#1]
The Tabs List plugin does not work well together with the Find in Files plugin: The Results tab has the wrong name "Untitled1" in the tabs list. And when changing tabs, CudaText hangs and must be killed with the task manager.

**Comment by Alexey-T** [comment]
tab-title update--Fixed, use "Install from Github". Confirm? Hang of tabchange:dont see, FIF may hang of loading the tab text- it is case?

**Comment by Alexey-T** [comment]
tab-title update: needs Cud, upload latr

**Comment by Andreas123456** [comment]
Please post again when you have made the upload. At the moment, the problem with the tab-title still occurs.

Regarding the hanging when changing tabs: It seems to be gone. I cannot reproduce it any more.

**Comment by Alexey-T** [comment]
Cud BT; now solved?

**Comment by Andreas123456** [comment]
It's solved. Thank you.
