### ISSUE TITLE
Update: *-mark, [NN] hidden

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_tabs_list#3]
@Andreas123456
Install Cud Beta: uvviewsoft.com/bb/
Install upd (AddonManager)

*-Mark shown for mod-tabs;
NN index hidden

Is it ok?

**Comment by Andreas123456** [comment]
Very good. But could you please increase (by factor 3 or 4) the number of spaces before [Tab1], [Tab2] etc.? The current number of spaces is too low. When the panel is broad, you'll see [Tab1], [Tab2], ...

**Comment by Alexey-T** [comment]
Fix/Upd, no spaces.. ok?

**Comment by Alexey-T** [comment]
more wishes? post?

**Comment by Alexey-T** [comment]
more wishes, welcome.

**Comment by Andreas123456** [comment]
For the Tabs List plugin, I have only one more wish: support of drag&drop in the panel.
